myffbad:
  url: https://www.myffbad.fr
  searchVerifyToken: ${SEARCH_VERIFY_TOKEN}
  detailsVerifyToken: ${SEARCH_DETAILS_TOKEN}

slack:
  token: ${SLACK_TOKEN}
  channel: ${SLACK_CHANNEL}

amazon:
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT}
  aws:
    accesskey: ${AWS_ACCESS_KEY}
    secretkey: ${AWS_SECRET_KEY}
