myffbad:
  url: https://www.myffbad.fr
  searchVerifyToken: ${SEARCH_VERIFY_TOKEN}
  detailsVerifyToken: ${DETAILS_VERIFY_TOKEN}

slack:
  token: ${SLACK_TOKEN}
  channel: ${SLACK_CHANNEL}

amazon:
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT}
    tablename:
      prefix: ${TABLENAME_PREFIX}
  aws:
    accesskey: ${DYNAMO_ACCESS_KEY}
    secretkey: ${DYNAMO_SECRET_KEY}
